name: bindgen-cli

on:
  push:
    branches:
      - bindgen-cli
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: bindgen-cli
      bin: bindgen
    permissions:
      attestations: write
      contents: write
      id-token: write
