name: cargo-fuzz

on:
  push:
    branches:
      - cargo-fuzz
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cargo-fuzz
    permissions:
      attestations: write
      contents: write
      id-token: write
