name: cargo-afl

on:
  push:
    branches:
      - cargo-afl
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cargo-afl
    permissions:
      id-token: write
      contents: write
      attestations: write
