name: cargo-web

on:
  push:
    branches:
      - cargo-web
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cargo-web
    permissions:
      attestations: write
      contents: write
      id-token: write
