name: cargo-llvm-lines

on:
  push:
    branches:
      - cargo-llvm-lines
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cargo-llvm-lines
    permissions:
      id-token: write
      contents: write
      attestations: write
    secrets: inherit
