name: cargo-outdated

on:
  push:
    branches:
      - cargo-outdated
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cargo-outdated
    permissions:
      id-token: write
      contents: write
      attestations: write
