name: cbindgen

on:
  push:
    branches:
      - cbindgen
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cbindgen
    permissions:
      id-token: write
      contents: write
      attestations: write
