name: cxxbridge-cmd

on:
  push:
    branches:
      - cxxbridge-cmd
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cxxbridge-cmd
      bin: cxxbridge
    permissions:
      attestations: write
      contents: write
      id-token: write
