name: dircnt

on:
  push:
    branches:
      - dircnt
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: dircnt
    permissions:
      id-token: write
      contents: write
      attestations: write
    secrets: inherit
