name: dotslash

on:
  push:
    branches:
      - dotslash
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: dotslash
    permissions:
      id-token: write
      contents: write
      attestations: write
