name: mdbook

on:
  push:
    branches:
      - mdbook
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: mdbook
    permissions:
      id-token: write
      contents: write
      attestations: write
