name: mdbook

on:
  push:
    branches:
      - mdbook
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: mdbook
      version: 0.4.41 # https://github.com/dtolnay/cxx/issues/1423
    permissions:
      contents: write
    secrets: inherit
