name: rustup-toolchain-install-master

on:
  push:
    branches:
      - rustup-toolchain-install-master
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: rustup-toolchain-install-master
      git: dtolnay-contrib/rustup-toolchain-install-master
      ref: nodefault
    permissions:
      id-token: write
      contents: write
      attestations: write
    secrets: inherit
