name: sha1dir

on:
  push:
    branches:
      - sha1dir
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: sha1dir
    permissions:
      attestations: write
      contents: write
      id-token: write
