name: star-history

on:
  push:
    branches:
      - star-history
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: star-history
    permissions:
      id-token: write
      contents: write
      attestations: write
    secrets: inherit
